# Generated by Django 5.0.4 on 2024-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Латинское название')),
                ('name_rus', models.CharField(max_length=100, null=True, verbose_name='Русское название')),
                ('ra', models.FloatField(verbose_name='Долгота,прямое восхождение (ra)')),
                ('dec', models.FloatField(verbose_name='Широта,склонение (dec)')),
            ],
            options={
                'verbose_name': 'Созвездие',
                'verbose_name_plural': 'Cозвездия',
            },
        ),
    ]
