# Generated by Django 5.0.4 on 2024-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ra', models.FloatField(verbose_name='Долгота(Прямое восхождение)')),
                ('dec', models.FloatField(verbose_name='Широта(склонение)')),
            ],
        ),
    ]
