# Generated by Django 5.0.4 on 2024-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constellation',
            options={'verbose_name': 'Созвездие', 'verbose_name_plural': 'Cозвездия'},
        ),
        migrations.AlterField(
            model_name='constellation',
            name='dec',
            field=models.FloatField(verbose_name='Широта,склонение (dec)'),
        ),
        migrations.AlterField(
            model_name='constellation',
            name='ra',
            field=models.FloatField(verbose_name='Долгота,прямое восхождение (ra)'),
        ),
    ]
