# Generated by Django 5.0.4 on 2024-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
